sudo: false
language: cpp
compiler: gcc
#python:
#  - "3.4"

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev

before_script:
  - pwd
  - mkdir build && cd build

script: cmake .. && make
